GET http://localhost:5047/api/movies

###

GET http://localhost:5047/api/movies?genre=Action

###
@movieId = 0d333906-9e5e-4d7d-b2a8-35aac837a428
GET http://localhost:5047/api/movies/{{movieId}}

###

POST http://localhost:5047/api/movies
Content-Type: application/json

{
  "title": "Dune",
  "genre": "SciFi",
  "director": "Denis Villeneuve",
  "releaseDate": "2021-10-22",
  "poster": "https://images.unsplash.com/photo-1501535033-a594139be346?q=80&w=1000&auto=format&fit=crop",
  "url": "https://www.youtube.com/watch?v=RZbACPsQLS4"
}

###

