GET http://localhost:5047/api/movies

###

POST http://localhost:5047/api/movies
Content-Type: application/json

{
  "title": "Spider-Man",
  "genre": "Action",
  "director": "Sam Raimi",
  "releaseDate": "2002-10-14"
}

###

